language: node_js
node_js:
- '10'
branches:
  except:
  - releases
deploy:
- provider: script
  skip_cleanup: true
  script: npm run release-to-branch
  on:
    branch: master
- provider: npm
  skip_cleanup: true
  email: npm@slicemenice.de
  api_key:
    secure: "AGgM2A83qoQHRYkMrsWSDeRTjJfuXtqLdCkIS4txIOtKlq4eEni7wc+In13YysgIOjjDmr5fdybQ8HOlimC6lY7o7Jio71njLr4a33uJJ0WnwsSpI3X+GBGHe2qve1fJxDmPeUuIgH2UI7GleCkv2OHWSgQ5tvrDpWnwVGmWHg8KtqH3oWMbHgF8W4/+4pFvRff7vcS5JuuHknulUXzYu3jD+ze9amnWN8Vvg4ZnPnoZa05l1FNGZJKrel921TopdxfMtQo2OgdysA+r+H+z1XDAvt2ZRiygJKVRxb3db8CIobJzcRZaVH4g4V6bicGx8p//ur79OdoVHOcZ3rQgd7kECXuQBiB5BHGq3b6y1mAs60Ln9QhqWjLdVeIR6FRj2oBKfboJh58Ko5vqZJixNQ4i7tvnV1T/CsH653NCxnd7063t9BO9idfMSDf5gZsDy/yog58YMs40lSzrZOM+dAN0cBsXdEUnCfUGpvIVUXKEXfSQVBocwr1IUFlEpHtBYZua8uZ0pgSjxHCkQmxEGQeGvLYY83+SjL3ig22ocOEXdQRbRkbveXg0JRq9AN9U8RyGhixOn34AzgIkuhGZGRH6h9yH6DES0tcLB1O4R4oatsvZ5HFeqexJzHGnJK0ToDzhtXBayOfu3oCVwKg9wuzPISBdDqkHuj8LsjozUH8="
  on:
    branch: releases
    tags: true